[package]
name = "rssat"
authors = ["Xie Zhongtao"]
version = "0.1.1"
edition = "2021"
keywords=["sat","minisat","cadical","glucose","slover"]
categories = ["science", "mathematics"]
description = "rssat is a Rust library that provides Rust bindings for multiple popular SAT solvers"
repository="https://github.com/francisol/rssat.git"
license="MIT"

[package.metadata.docs.rs]

features = [""]


# Whether to pass `--no-default-features` to Cargo (default: false)
no-default-features = true

# Target to test build on, used as the default landing page (default: "x86_64-unknown-linux-gnu")
#
# Any target supported by rustup can be used.
default-target = "x86_64-unknown-linux-gnu"

[dependencies]

[build-dependencies]
bindgen = "0.70.1"
cmake = "0.1"
reqwest = { version = "0.12", features = ["blocking","rustls-tls"], default-features = false }
flate2 = "1.0"
tar = "0.4"
[features]
default = ["glucose","minisat","cadical"]
cadical = []
minisat = []
glucose = []

