[package]
name = "rssat"
version = "0.1.0"
edition = "2021"

[dependencies]

[build-dependencies]
bindgen = "0.70.1"
cmake = "0.1"
reqwest = { version = "0.12", features = ["blocking","rustls-tls"], default-features = false }
flate2 = "1.0"
tar = "0.4"
[features]
default = ["glucose","minisat","cadical"]
cadical = []
minisat = []
glucose = []
